my.bk/back/models.py
from datetime import datetime

from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class User(db.Model):
    name = db.Column(db.String(25),primary_key=True)
    password = db.Column(db.String(255),nullable=False)
    number = db.Column(db.String(25),nullable=False)
    email = db.Column(db.String(25),nullable=False)
    create_time = db.Column(db.DateTime,default=datetime.now)

    __tablename__ = 'yh'

    #保存功能
    def save(self):
        db.session.add(self)
        db.session.commit()


class LanMu(db.Model):
    id = db.Column(db.String(30),primary_key=True)
    bieming = db.Column(db.String(30), nullable=False)
    gjz = db.Column(db.String(50),nullable=False)
    miaoshu = db.Column(db.TEXT,nullable=False)
    __tablename__ = 'lanmu'


class WZ(db.Model):
    id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    title = db.Column(db.String(50), nullable=False)
    nr = db.Column(db.TEXT,nullable=False)
    ms = db.Column(db.TEXT,nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)

    __tablename__ = 'wenzhang'

my.bk/back/views.py
from flask import Blueprint, request, render_template, redirect, url_for, session
from werkzeug.security import generate_password_hash, check_password_hash


#验证密码的 jianjiatow

#第一步生成蓝图，用于管理路由
from back.models import User, LanMu, db, WZ
from utils.functions import is_login

back_blue = Blueprint('back',__name__)

#第二步 ： 使用蓝图对象管理路由

#首页
@back_blue.route('/',methods=['GET','POST'])
def home():
    if request.method =='GET':
        return render_template('back/login.html')
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        print(username,password)
        user = User.query.filter(User.name == username).first()
        if not user:
            error = '用户名不存在'
            return render_template('back/login.html',error=error)
        if not check_password_hash(user.password, password):
            error = '密码错误'
            return render_template('back/login.html',error=error)
        session['user_id'] = user.name
        return redirect(url_for('back.index'))

#注册
@back_blue.route('/register/',methods=['GET','POST'])
def register():
    if request.method == 'GET':
        return render_template('back/register.html')
    if request.method == 'POST':
        #获取数据
        username = request.form.get('username')
        password = request.form.get('password')
        password1 = request.form.get('password1')
        number = request.form.get('number')
        email = request.form.get('email')
        # 判断用户名是否注册过，如果注册在判断密码
        user = User.query.filter(User.name == username).first()
        if user:
            #用户存在
            error = '用户名已存在'
            return render_template('back/register.html', error = error)
        else:
            if password1 == password:
                #保存数据
                user = User()
                user.name = username
                # user.password = password
                #给密码编码
                user.password = generate_password_hash(password)
                user.email = email
                user.number = number
                user.save()
                return redirect(url_for('back.home'))
            else:
                #密码不一样
                error='两次输入的密码不一致'
                return render_template('back/register.html',error=error)

#得到博客主页
@back_blue.route('/index/',methods=['GET'])
@is_login
def index():
    if request.method == 'GET':
        return render_template('back/index.html', error=session.get('user_id'))


@back_blue.route('/delete/',methods=['GET'])
def delete():
    if request.method == 'GET':
        session.pop('user_id')  #删除session
        return redirect(url_for('back.home'))


@back_blue.route('/wenzhang/',methods=['GET','POST'])
@is_login
def wenzhang():
    if request.method == 'GET':
        types = WZ.query.all()
        return render_template('back/add-article.html', error=session.get('user_id'), types=types)
    if request.method == 'POST':
        title = request.form.get('title')
        nr = request.form.get('nr')
        ms = request.form.get('ms')
        if not (title and nr and ms):
            errtr = '请完整输入'
            return render_template('back/add-article.html', errtr=errtr)
        else:
            w = WZ()
            w.title = title
            w.nr = nr
            w.ms = ms
            db.session.add(w)
            db.session.commit()
            return redirect(url_for('back.wenzhang'))



@back_blue.route('/gonggao/',methods=['GET'])
@is_login
def gonggao():
    if request.method == 'GET':
        return render_template('back/add-notice.html',error=session.get('user_id'))

#文章列表
@back_blue.route('/wzlist/',methods=['GET'])
@is_login
def pinglun():
    if request.method == 'GET':
        types = WZ.query.all()
        page = request.args.get('page', 1, type=int)
        pagination = WZ.query.order_by(WZ.create_time.desc()).paginate(page, per_page=2, error_out=False)
        users = pagination.items
        print(pagination)
        print(users)
        return render_template('back/comment.html', error=session.get('user_id'), users=users, pagination=pagination)

#文章删除
@is_login
@back_blue.route('/del_wz/<int:id>/', methods=['GET'])
def del_wz(id):
    #从数据库里找到id一样的一行完整数据，
    type = WZ.query.get(id)
    db.session.delete(type) #删除
    db.session.commit()
    return redirect(url_for('back.pinglun'))

#栏目的添加
@back_blue.route('/lanmu/',methods=['GET','POST'])
@is_login
def lanmu():
    if request.method == 'GET':
        types = LanMu.query.all()
        return render_template('back/category.html', error=session.get('user_id'), types=types)
    if request.method =='POST':
        name = request.form.get('name')
        bm = request.form.get('bm')
        gjz = request.form.get('gjz')
        ms = request.form.get('ms')
        #保存栏目信息
        LM = LanMu()
        LM.id = name
        LM.bieming = bm
        LM.gjz = gjz
        LM.miaoshu = ms
        db.session.add(LM)
        db.session.commit()
        return redirect(url_for('back.lanmu'))

#栏目删除
@is_login
@back_blue.route('/del_lanmu/<string:id>/',methods=['GET'])
def del_type(id):
    #从数据库里找到id一样的一行完整数据，
    atype = LanMu.query.get(id)
    db.session.delete(atype) #删除
    db.session.commit()
    return redirect(url_for('back.lanmu'))

@is_login
@back_blue.route('/xiugai/<string:id>/',methods=['GET','POST'])
def undate_lanmu(id):
    if request.method == 'GET':
        return render_template('back/xiugai.html')
    if request.method == 'POST':
        name = request.form.get('name')
        bm = request.form.get('bm')
        gjz = request.form.get('gjz')
        ms = request.form.get('ms')
        #从数据库里找到id一样的一行数据
        atype = LanMu.query.get(id)
        # print(atype)
        atype.id = name
        atype.bieming = bm
        atype.gjz = gjz
        atype.miaoshu = ms
        #添加  提交
        db.session.add(atype)
        db.session.commit()
        return redirect(url_for('back.lanmu'))

my.bk/web/views.py
from flask import Blueprint, request,\
    render_template, redirect, url_for

#第一步 ：生成蓝图对象
#蓝图用于管理路由
web_blue = Blueprint('first', __name__)



@web_blue.route('/' , methods=['GET'])
def shouye():
    if request.method == 'GET':
        return render_template('web/index.html')


@web_blue.route('/about/',methods=['GET'])
def one():
    if request.method == 'GET':
        return render_template('web/about.html')

@web_blue.route('/share/',methods=['GET'])
def two():
    if request.method == 'GET':
        return render_template('web/share.html')

@web_blue.route('/leixing/',methods=['GET'])
def three():
    if request.method == 'GET':
        return render_template('web/list.html')

@web_blue.route('/fanju/',methods=['GET'])
def four():
    if request.method == 'GET':
        return render_template('web/life.html')

@web_blue.route('/shenzuo/',methods=['GET'])
def five():
    if request.method == 'GET':
        return render_template('web/time.html')


@web_blue.route('/liuyan/',methods=['GET'])
def six():
    if request.method == 'GET':
        return render_template('web/gbook.html')

@web_blue.route('/neirong/',methods=['GET'])
def server():
    if request.method == 'GET':
        return render_template('web/info.html')

my.bk/templates/back/base.html
{{ ex}}

my.bk/templates/web/gbook.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_肖誉个人博客 </title>
<!--反向解析写法-->
  <link href="{{ url_for('static',filename='css/base.css')}}" rel="stylesheet">
  <link href="{{ url_for('static',filename='css/index.css')}}" rel="stylesheet">
  <link href="{{ url_for('static',filename='css/m.css')}}" rel="stylesheet">


  <script src="{{ url_for('static',filename='js/jquery.min.js')}}" type="text/javascript"></script>
  <script src="{{ url_for('static',filename='js/jquery.easyfader.min.js')}}" type="text/javascript"></script>
  <script src="{{ url_for('static',filename='js/scrollReveal.js')}}" type="text/javascript"></script>
  <script src="{{ url_for('static',filename='js/common.js')}}" type="text/javascript"></script>

</head>
<body>
<header> 
  <!--menu begin-->
  <div class="menu">
    <nav class="nav" id="topnav">
      <h1 class="logo"><a href="">肖誉的个人二次元</a></h1>
      <li><a href="{{ url_for('first.shouye')}}">网站首页</a> </li>
      <li><a href="{{ url_for('first.one')}}">国产</a> </li>
      <li><a href="{{ url_for('first.two')}}">地区</a>
        <ul class="sub-nav">
          <li><a href="share">中国</a></li>
          <li><a href="share">日本</a></li>
          <li><a href="share">欧美</a></li>
        </ul>
      </li>
      <li><a href="{{ url_for('first.three')}}">类型</a>
        <ul class="sub-nav">
          <li><a href="list.html">恋爱</a></li>
          <li><a href="list.html">热血</a></li>
          <li><a href="list.html">治愈</a></li>
          <li><a href="list.html">日常</a></li>
          <li><a href="list.html">搞笑</a></li>
        </ul>
      </li>
      <li><a href="{{ url_for('first.four')}}">番剧</a>
        <ul class="sub-nav">
          <li><a href="life.html">2017年4月新番</a></li>
          <li><a href="life.html">2017年10月新番</a></li>
          <li><a href="life.html">2017年12月新番</a></li>
          <li><a href="life.html">2018年2月新番</a></li>
        </ul>
       <li><a href="{{ url_for('first.five')}}">个人认为的神作</a> </li>
      <li><a href="{{ url_for('first.six')}}">留言</a> </li>
      <li><a href="{{ url_for('first.server')}}">内容</a> </li>

      <!--search begin-->
      <div id="search_bar" class="search_bar">
        <form  id="searchform" action="[!--news.url--]e/search/index.php" method="post" name="searchform">
          <input class="input" placeholder="想搜点什么呢..." type="text" name="keyboard" id="keyboard">
          <input type="hidden" name="show" value="title" />
          <input type="hidden" name="tempid" value="1" />
          <input type="hidden" name="tbname" value="news">
          <input type="hidden" name="Submit" value="搜索" />
          <span class="search_ico"></span>
        </form>
      </div>
      <!--search end--> 
    </nav>
  </div>
  <!--menu end--> 
  <!--mnav begin-->
  <div id="mnav">
    <h2><a href="http://www.yangqq.com" class="mlogo">杨青博客</a><span class="navicon"></span></h2>
    <dl class="list_dl">
      <dt class="list_dt"> <a href="index.html">网站首页</a> </dt>
      <dt class="list_dt"> <a href="about.html">关于我</a> </dt>
      <dt class="list_dt"> <a href="#">模板分享</a> </dt>
      <dd class="list_dd">
        <ul>
          <li><a href="share.html">个人博客模板</a></li>
          <li><a href="share.html">国外Html5模板</a></li>
          <li><a href="share.html">企业网站模板</a></li>
        </ul>
      </dd>
      <dt class="list_dt"> <a href="#">学无止境</a> </dt>
      <dd class="list_dd">
        <ul>
          <li><a href="list.html">心得笔记</a></li>
          <li><a href="list.html">CSS3|Html5</a></li>
          <li><a href="list.html">网站建设</a></li>
          <li><a href="list.html">推荐工具</a></li>
          <li><a href="list.html">JS实例索引</a></li>
        </ul>
      </dd>
      <dt class="list_dt"> <a href="#">慢生活</a> </dt>
      <dd class="list_dd">
        <ul>
          <li><a href="life.html">日记</a></li>
          <li><a href="life.html">欣赏</a></li>
          <li><a href="life.html">程序人生</a></li>
          <li><a href="life.html">经典语录</a></li>
        </ul>
      </dd>
      <dt class="list_dt"> <a href="time.html">时间轴</a> </dt>
      <dt class="list_dt"> <a href="gbook.html">留言</a> </dt>
    </dl>
  </div>
  <!--mnav end--> 
</header>
<div class="pagebg ab"> </div>
<div class="container">
  <h1 class="t_nav"><span>你，我生命中一个重要的过客，我们之所以是过客，因为你未曾会为我停留。</span><a href="/" class="n1">网站首页</a><a href="/" class="n2">留言</a></h1>
  <div class="news_infos">
    <ul>
      此处安装评论插件
    </ul>
  </div>
  <div class="sidebar">
    <div class="about">
      <p class="avatar"> <img src="images/avatar.jpg" alt=""> </p>
      <p class="abname">dancesmile | 杨青</p>
      <p class="abposition">Web前端设计师、网页设计</p>
      <p class="abtext"> 一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。 </p>
    </div>
    <div class="weixin">
      <h2 class="hometitle">微信关注</h2>
      <ul>
        <img src="images/wx.jpg">
      </ul>
    </div>
  </div>
</div>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>

my.bk/templates/web/index.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_肖誉个人博客 </title>
<!--反向解析写法-->
  <link href="{{ url_for('static',filename='css/base.css')}}" rel="stylesheet">
  <link href="{{ url_for('static',filename='css/index.css')}}" rel="stylesheet">
  <link href="{{ url_for('static',filename='css/m.css')}}" rel="stylesheet">


  <script src="{{ url_for('static',filename='js/jquery.min.js')}}" type="text/javascript"></script>
  <script src="{{ url_for('static',filename='js/jquery.easyfader.min.js')}}" type="text/javascript"></script>
  <script src="{{ url_for('static',filename='js/scrollReveal.js')}}" type="text/javascript"></script>
  <script src="{{ url_for('static',filename='js/common.js')}}" type="text/javascript"></script>
</head>
<body>
<header> 
  <!--menu begin-->
  <div class="menu">
    <nav class="nav" id="topnav">
      <h1 class="logo"><a href="{{ url_for('first.shouye')}}">肖誉的个人二次元</a></h1>
      <li><a href="{{ url_for('first.shouye')}}">网站首页</a> </li>
      <li><a href="{{ url_for('first.one')}}">国产</a> </li>
      <li><a href="{{ url_for('first.two')}}">地区</a>
        <ul class="sub-nav">
          <li><a href="share">中国</a></li>
          <li><a href="share">日本</a></li>
          <li><a href="share">欧美</a></li>
        </ul>
      </li>
      <li><a href="{{ url_for('first.three')}}">类型</a>
        <ul class="sub-nav">
          <li><a href="list.html">恋爱</a></li>
          <li><a href="list.html">热血</a></li>
          <li><a href="list.html">治愈</a></li>
          <li><a href="list.html">日常</a></li>
          <li><a href="list.html">搞笑</a></li>
        </ul>
      </li>
      <li><a href="{{ url_for('first.four')}}">番剧</a>
        <ul class="sub-nav">
          <li><a href="life.html">2017年4月新番</a></li>
          <li><a href="life.html">2017年10月新番</a></li>
          <li><a href="life.html">2017年12月新番</a></li>
          <li><a href="life.html">2018年2月新番</a></li>
        </ul>
       <li><a href="{{ url_for('first.five')}}">个人认为的神作</a> </li>
      <li><a href="{{ url_for('first.six')}}">留言</a> </li>
      <li><a href="{{ url_for('first.server')}}">内容</a> </li>


    </nav>
  </div>

</header>
<article> 
  <!--banner begin-->
 <div class="picsbox"> 
  <div class="banner">
    <div id="banner" class="fader">
      <li class="slide" ><a href="/" target="_blank"><img src="../static/images/hy.jpg"><span class="imginfo">火影忍者</span></a></li>
      <li class="slide" ><a href="/" target="_blank"><img src="../static/images/海贼.jpg"><span class="imginfo">航海王</span></a></li>
      <li class="slide" ><a href="/" target="_blank"><img src="../static/images/kn.jpg"><span class="imginfo">名侦探柯南</span></a></li>
      <li class="slide" ><a href="/" target="_blank"><img src="../static/images/yj.jpg"><span class="imginfo">妖精的尾巴</span></a></li>
      <div class="fader_controls">
        <div class="page prev" data-target="prev">&lsaquo;</div>
        <div class="page next" data-target="next">&rsaquo;</div>
        <ul class="pager_list">
        </ul>
      </div>
    </div>
  </div>
  <!--banner end-->
  <div class="toppic">
    <li> <a href="/" target="_blank"> <i><img src="{{ url_for('static',filename='images/cw.jpg')}}"></i>
      <h2>樱花庄的宠物女孩</h2></a> </li>
      <!--<span></span> -->
    <li> <a href="/" target="_blank"> <i><img src="{{ url_for('static',filename='images/sy.jpg')}}"></i>
      <h2>四月是你的谎言</h2></a> </li>
      <!--<span>学无止境</span> -->
  </div>
  </div>
  <div class="blank"></div>
  <!--blogsbox begin-->
  <div class="blogsbox">
    <div class="blogs" data-scroll-reveal="enter bottom over 1s" >
      <h3 class="blogtitle"><a href="/" target="_blank">刀剑神域第一季</a></h3>
      <span class="blogpic"><a href="/" title=""><img src="{{ url_for('static',filename='images/dj.jpg')}}" alt=""></a></span>
      <p class="blogtext">这是我的入宅作，记得当时好像才初3吧...</p>
      <div class="bloginfo">
        <ul>
          <li class="author"><a href="{{ url_for('first.shouye')}}">肖誉</a></li>
          <li class="lmname"><a href="{{ url_for('first.shouye')}}">一场关于生死的游戏</a></li>
          <li class="timer">2018-5-13</li>
          <li class="view"><span>34567</span>已阅读</li>
          <li class="like">9999</li>
        </ul>
      </div>
    </div>
    <div class="blogs" data-scroll-reveal="enter bottom over 1s" >
      <h3 class="blogtitle"><a href="{{ url_for('first.shouye')}}" target="_blank"><img src="{{ url_for('static',filename='images/fate1.jpg')}}" alt="">Fate/stay night</a></h3>
      <p class="blogtext">一场圣杯之战就此开始...</p>
      <div class="bloginfo">
        <ul>
          <li class="author"><a href="{{ url_for('first.shouye')}}">肖誉</a></li>
          <li class="lmname"><a href="{{ url_for('first.shouye')}}">一场关于荣耀的决战</a></li>
          <li class="timer">2018-5-13</li>
          <li class="view">4567已阅读</li>
          <li class="like">9999</li>
        </ul>
      </div>
    </div>
    <div class="blogs" data-scroll-reveal="enter bottom over 1s" >
      <h3 class="blogtitle"><a href="{{ url_for('first.shouye')}}" target="_blank">我的英雄学院</a></h3>
      <span class="bplist"><a href="{{ url_for('first.shouye')}}" title="">
      <li><img src="{{ url_for('static',filename='images/yx.jpg')}}" alt=""></li>
      <li><img src="{{ url_for('static',filename='images/yx1.png')}}" alt=""></li>
      <li><img src="{{ url_for('static',filename='images/yx2.png')}}" alt=""></li>
      </a></span>
      <p class="blogtext">这一刻，你就是英雄！！！ </p>
      <div class="bloginfo">
        <ul>
          <li class="author"><a href="/">肖誉</a></li>
          <li class="lmname"><a href="/">什么才是英雄？</a></li>
          <li class="timer">2018-5-13</li>
          <li class="view"><span>34567</span>已阅读</li>
          <li class="like">9999</li>
        </ul>
      </div>
    </div>
    <div class="blogs" data-scroll-reveal="enter bottom over 1s" >
      <h3 class="blogtitle"><a href="{{ url_for('first.shouye')}}" target="_blank">哆啦a梦</a></h3>
      <span class="bigpic"><a href="{{ url_for('first.shouye')}}" title=""><img src="{{ url_for('static',filename='images/dl.jpg')}}" alt=""></a></span>
      <p class="blogtext">谁不想要个蓝胖子呢... </p>
      <div class="bloginfo">
        <ul>
          <li class="author"><a href="{{ url_for('first.shouye')}}">肖誉</a></li>
          <li class="lmname"><a href="{{ url_for('first.shouye')}}">蓝胖子</a></li>
          <li class="timer">2018-5-13</li>
          <li class="view"><span>34567</span>已阅读</li>
          <li class="like">9999</li>
        </ul>
      </div>
    </div>
     <div class="blogs" data-scroll-reveal="enter bottom over 1s" >
      <h3 class="blogtitle"><a href="{{ url_for('first.shouye')}}" target="_blank">Another</a></h3>
      <span class="bigpic"><a href="{{ url_for('first.shouye')}}" title=""><img src="{{ url_for('static',filename='images/another.jpg')}}" alt=""></a></span>
      <p class="blogtext">强烈推荐：Another </p>
      <div class="bloginfo">
        <ul>
          <li class="author"><a href="{{ url_for('first.shouye')}}">肖誉</a></li>
          <li class="lmname"><a href="{{ url_for('first.shouye')}}">蓝胖子</a></li>
          <li class="timer">2018-5-13</li>
          <li class="view"><span>34567</span>已阅读</li>
          <li class="like">9999</li>
        </ul>
      </div>
    </div>
     <div class="blogs" data-scroll-reveal="enter bottom over 1s" >
      <h3 class="blogtitle"><a href="{{ url_for('first.shouye')}}" target="_blank">哆啦a梦</a></h3>
      <span class="bigpic"><a href="{{ url_for('first.shouye')}}" title=""><img src="{{ url_for('static',filename='images/dl.jpg')}}" alt=""></a></span>
      <p class="blogtext">谁不想要个蓝胖子呢... </p>
      <div class="bloginfo">
        <ul>
          <li class="author"><a href="{{ url_for('first.shouye')}}">肖誉</a></li>
          <li class="lmname"><a href="{{ url_for('first.shouye')}}">蓝胖子</a></li>
          <li class="timer">2018-5-13</li>
          <li class="view"><span>34567</span>已阅读</li>
          <li class="like">9999</li>
        </ul>
      </div>
    </div>






  </div>
  <!--blogsbox end-->
  <div class="sidebar">
    <div class="zhuanti">
      <h2 class="hometitle">特别推荐</h2>
      <ul>
        <li> <i><img src="{{ url_for('static',filename='images/jj.jpg')}}"></i>
          <p>进击的巨人<span><a href="/">阅读</a></span> </p>
        </li>
        <li> <i><img src="{{ url_for('static',filename='images/another.jpg')}}"></i>
          <p>Another <span><a href="/">阅读</a></span></p>
        </li>
        <li> <i><img src="{{ url_for('static',filename='images/another1.jpg')}}"></i>
          <p>Another <span><a href="/">阅读</a></span></p>
        </li>
      </ul>
    </div>
    <div class="tuijian">
      <h2 class="hometitle">推荐文章</h2>
      <ul class="tjpic">
        <i><img src="{{ url_for('static',filename='images/another.jpg')}}"></i>
        <p><a href="/">有点恐怖，血腥</a></p>
      </ul>
      <ul class="sidenews">
        <li> <i><img src="{{ url_for('static',filename='images/another1.jpg')}}"></i>
          <p><a href="/">邓文新打游戏真tm想蔡徐坤！</a></p>
          <span>2018-05-13</span> </li>
        <li> <i><img src="{{ url_for('static',filename='images/another1.jpg')}}"></i>
          <p><a href="/">杨岩打游戏真tm想蔡徐坤！</a></p>
          <span>2018-05-13</span> </li>
        <li> <i><img src="{{ url_for('static',filename='images/another1.jpg')}}"></i>
          <p><a href="/">熊慧杨打游戏真tm想蔡徐坤！</a></p>
          <span>2018-05-13</span> </li>
        <li> <i><img src="{{ url_for('static',filename='images/another1.jpg')}}"></i>
          <p><a href="/">上面三个渣渣！</a></p>
          <span>2018-05-13</span> </li>
      </ul>
    </div>
    <div class="tuijian">
      <h2 class="hometitle">动漫排行</h2>
      <ul class="tjpic">
        <i><img src="{{ url_for('static',filename='images/hy.jpg')}}"></i>
        <p><a href="/">火影忍者</a></p>
      </ul>
      <ul class="sidenews">
        <li> <i><img src="{{ url_for('static',filename='images/hy.jpg')}}"></i>
          <p><a href="/">火影忍者</a></p>
          <span>2018-05-13</span> </li>
        <li> <i><img src="{{ url_for('static',filename='images/hy.jpg')}}"></i>
          <p><a href="/">火影忍者</a></p>
          <span>2018-05-13</span> </li>
        <li> <i><img src="{{ url_for('static',filename='images/hy.jpg')}}"></i>
          <p><a href="/">火影忍者</a></p>
          <span>2018-05-13</span> </li>
        <li> <i><img src="{{ url_for('static',filename='images/hy.jpg')}}"></i>
          <p><a href="/">火影忍者</a></p>
          <span>2018-05-13</span> </li>
      </ul>
    </div>
    <div class="cloud">
      <h2 class="hometitle">标签云</h2>
      <ul>
        <a href="/">陌上花开</a> <a href="/">校园生活</a> <a href="/">html5</a> <a href="/">SumSung</a> <a href="/">青春</a> <a href="/">温暖</a> <a href="/">阳光</a> <a href="/">三星</a><a href="/">索尼</a> <a href="/">华维荣耀</a> <a href="/">三星</a> <a href="/">索尼</a>
      </ul>
    </div>
    <div class="links">
      <h2 class="hometitle">友情链接</h2>
      <ul>
        <li><a href="http://www.yangqq.com" target="_blank">肖誉博客</a></li>
        <li><a href="http://www.yangqq.com" target="_blank">设计师博客</a></li>
        <li><a href="http://www.yangqq.com" target="_blank">优秀个人博客</a></li>
      </ul>
    </div>
    <div class="guanzhu" id="follow-us">
      <h2 class="hometitle">关注我们 么么哒！</h2>
      <ul>
        <li class="sina"><a href="/" target="_blank"><span>新浪微博</span>肖誉博客</a></li>
        <li class="tencent"><a href="/" target="_blank"><span>腾讯微博</span>肖誉博客</a></li>
        <li class="qq"><a href="/" target="_blank"><span>QQ号</span>1803352740</a></li>
        <li class="email"><a href="/" target="_blank"><span>邮箱帐号</span>1803352740@qq.com</a></li>
        <li class="wxgzh"><a href="/" target="_blank"><span>微信号</span>1803352740</a></li>

      </ul>
    </div>
  </div>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>