ttsx/carts/urls.py
from django.urls import path

from carts.views import *

urlpatterns = [
    path('index/',index,name='index'),

]

ttsx/goods/urls.py
from django.urls import path

from goods.views import *

urlpatterns = [
    path('index/', index, name='index'),
    path('goodlist/', goodlist, name='goodlist'),
    path('detail/', detail, name='detail'),
]

ttsx/ttsx/urls.py
from django.contrib import admin

from django.urls import path, include

from django.contrib.staticfiles.urls import static

from ttsx.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include(('user.urls', 'user'),namespace='user')),
    path('carts/',include(('carts.urls', 'carts'),namespace='carts')),
    path('goods/',include(('goods.urls', 'goods'),namespace='goods')),
    path('order/',include(('order.urls', 'order'),namespace='order')),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

ttsx/user/urls.py
from django.urls import path

from user.views import *

urlpatterns = [
    path('index/',index, name='index'),
    path('login/',login, name='login'),
    path('register/',register, name='register'),
    path('logout/',logout, name='logout'),
    path('UserCenter/', UserCenter, name='UserCenter'),

]

ttsx/carts/models.py
from django.db import models

from goods.models import Goods
from user.models import User


class ShoppingCart(models.Model):
    """
    购物车
    """
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
    nums = models.IntegerField(default=0, verbose_name='数量')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
    is_select = models.BooleanField(default=True)

    class Meta:
        db_table = 'f_shopping_cart'

ttsx/carts/views.py
from django.shortcuts import render

# Create your views here.
from utils.functions import session_login


# @session_login
def index(request):
    if request.method == 'GET':

        return render(request, 'cart.html')

ttsx/templates/11.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{#    {{ errors }}#}
    <form action="" method="post" enctype="multipart/form-data">
        <input type="text" name="name">
        <p>头像:<input type="file" name="icon" value="选择文件"></p>
        <p><input  type="submit" value="提交"></p>
    </form>
</body>
</html>

ttsx/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
    {% block aa %}
    {% endblock %}

    {% block body %}
    {% endblock %}

    {% block bb %}
    {% endblock %}

</body>
</html>

ttsx/templates/base_main.html
{% extends 'base.html' %}

{% block title %}天天生鲜{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
     <script type="text/javascript" src="{% static 'js/jquery-ui.min.js'%}"></script>
     <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock %}

{% block aa %}
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">

                {% if user %}
				<div class="login_info fl">
					欢迎您：<em>{{ user }}</em>
				</div>
                <div class="login_btn fl">
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出登录</a>
                </div>
                {% else %}
				<div class="login_btn fl">
                    <span>|</span>
					<a href="{% url 'user:login' %}">登录</a>
                </div>
                {% endif %}


				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:UserCenter' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'carts:index' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'goods:index' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
    {% endblock %}


    {% block body %}
	<div class="search_bar clearfix">
		<a href="{% url 'user:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'carts:index' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="{% url 'user:index' %}">首页</a></li>
				<li class="interval">|</li>
                <li><a href="{% url 'goods:goodlist' %}">商品列表</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg"></a>
			<a href="#"><img src="/static/images/adv02.jpg"></a>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">新鲜水果</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">鲜芒</a>
				<a href="#">加州提子</a>
				<a href="#">亚马逊牛油果</a>
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner01.jpg"></div>
			<ul class="goods_list fl">
				<li>
					<h4><a href="#">草莓</a></h4>
					<a href="#"><img src="/static/images/goods/goods003.jpg"></a>
					<div class="prize">¥ 30.00</div>
				</li>
				<li>
					<h4><a href="#">葡萄</a></h4>
					<a href="#"><img src="/static/images/goods/goods002.jpg"></a>
					<div class="prize">¥ 5.50</div>
				</li>
				<li>
					<h4><a href="#">柠檬</a></h4>
					<a href="#"><img src="/static/images/goods/goods001.jpg"></a>
					<div class="prize">¥ 3.90</div>
				</li>
				<li>
					<h4><a href="#">奇异果</a></h4>
					<a href="#"><img src="/static/images/goods/goods012.jpg"></a>
					<div class="prize">¥ 25.80</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">海鲜水产</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">河虾</a>
				<a href="#">扇贝</a>
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner02.jpg"></div>
			<ul class="goods_list fl">
				<li>
					<h4><a href="#">青岛野生海捕大青虾</a></h4>
					<a href="#"><img src="/static/images/goods/goods018.jpg"></a>
					<div class="prize">¥ 48.00</div>
				</li>
				<li>
					<h4><a href="#">扇贝</a></h4>
					<a href="#"><img src="/static/images/goods/goods019.jpg"></a>
					<div class="prize">¥ 46.00</div>
				</li>
				<li>
					<h4><a href="#">冷冻秋刀鱼</a></h4>
					<a href="#"><img src="/static/images/goods/goods020.jpg"></a>
					<div class="prize">¥ 19.00</div>
				</li>
				<li>
					<h4><a href="#">基围虾</a></h4>
					<a href="#"><img src="/static/images/goods/goods021.jpg"></a>
					<div class="prize">¥ 25.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model03">猪牛羊肉</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">鲜芒</a>
				<a href="#">加州提子</a>
				<a href="#">亚马逊牛油果</a>
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner03.jpg"></div>
			<ul class="goods_list fl">
				<li>
					<h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model04">禽类蛋品</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">鲜芒</a>
				<a href="#">加州提子</a>
				<a href="#">亚马逊牛油果</a>
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner04.jpg"></div>
			<ul class="goods_list fl">
				<li>
					<h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model05">新鲜蔬菜</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">鲜芒</a>
				<a href="#">加州提子</a>
				<a href="#">亚马逊牛油果</a>
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner05.jpg"></div>
			<ul class="goods_list fl">
				<li>
					<h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model06">速冻食品</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">鲜芒</a>
				<a href="#">加州提子</a>
				<a href="#">亚马逊牛油果</a>
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner06.jpg"></div>
			<ul class="goods_list fl">
				<li>
					<h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="/static/images/goods.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>


	<script type="text/javascript" src="js/slideshow.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock %}

{% block bb %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

    <script>
    if (session['user_id']==null){
        console.log('aaa')
    }

    </script>
     {% endblock %}

ttsx/templates/list.html
{% extends 'base_main.html' %}

{% block title %}
    商品列表
{% endblock %}


    {% block body %}
	<div class="search_bar clearfix">
		<a href="{% url 'user:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'carts:index' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
                {% for i in new_user %}
				<ul>
					<li>
						<a href="{% url 'goods:detail' %}?id={{ i.id }}"><img src="/{{ i.goods_front_image }}"></a>
						<h4><a href="{% url 'goods:detail' %}?id={{ i.id }}">{{ i.name }}</a></h4>
						<div class="prize">￥{{ i.shop_price }}</div>
					</li>
				</ul>
                {% endfor %}
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="#" class="active">默认</a>
				<a href="#">价格</a>
				<a href="#">人气</a>
			</div>


			<ul class="goods_type_list clearfix">

                {% for i in users %}
				<li>
					<a href="{% url 'goods:detail' %}?id={{ i.id }}"><img src="/{{ i.goods_front_image }}"></a>
					<h4><a href="{% url 'goods:detail' %}?page={{ i.id }}">{{ i.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ i.shop_price }}</span>
						<span class="unit">{{ i.shop_price }}/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
				{% if users.has_previous%}
					<a href="{% url 'goods:goodlist' %}?page={{ users.previous_page_number }}">上一页</a>
                {% endif %}


                {% for i in users.paginator.page_range %}
                    <a href="{% url 'goods:goodlist' %}?page={{ i }}"  class="active">{{ i }}</a>
                {% endfor %}


				 {% if users.has_next %}
					    <a href="{% url 'goods:goodlist' %}?page={{ users.next_page_number }}">下一页</a>
                    {% endif %}

			</div>
		</div>
	</div>
    {% endblock %}

ttsx/templates/login.html
{% extends 'index.html' %}

{% block title %}
    登录
{% endblock %}

{% block aa %}
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">

                {% if user %}
				<div class="login_info fl">
					欢迎您：<em>{{ user }}</em>
				</div>
                <div class="login_btn fl">
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出登录</a>
                </div>
                {% else %}
				<div class="login_btn fl">
                    <span>|</span>
					<a href="{% url 'user:login' %}">登录</a>
                </div>
                {% endif %}


				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:UserCenter' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'carts:index' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'goods:index' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}





{% block body %}
	<div class="login_top clearfix">
		<a href="{% url 'user:index' %}" class="login_logo"><img src="/static/images/logo.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					{% block a%}
                    <h1>用户登录</h1>
                     {% endblock %}
                        {% block b %}
					<a href="{% url 'user:register' %}">立即注册</a>
                        {% endblock %}
				</div>
				<div class="form_input">

                    {% block c %}
					<form action="" method="post">

						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">{{ errors.username }}</div>

						<input type="password" name="password" class="pass_input" placeholder="请输入密码">

						<div class="pwd_error">{{ errors.password }}{{ pwd_error }}</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
                        <input type="submit" name="" value="登录" class="input_submit">
                    </form>
                    {% endblock %}

				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
{% endblock %}

{% block bb %}
{% endblock %}

ttsx/templates/user_center_info.html
{% extends 'base_main.html' %}

{% block title %}用户中心{% endblock %}




{% block body %}
	<div class="search_bar clearfix">
		<a href="{% url 'user:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:UserCenter' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'goods:index' %}">· 全部订单</a></li>
				<li><a href="{% url 'order:index' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>18210569700</li>
							<li><span>联系方式：</span>18210569700</li>
							<li><span>联系地址：</span>北京市昌平区</li>
						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                {% for i in gs %}
				<li>
					<a href="{% url 'goods:detail' %}?id={{ i.goodsid.id }}"><img src="/{{ i.goodsid.goods_front_image }}"></a>
					<h4><a href="{% url 'goods:detail' %}?id={{ i.goodsid.id }}">{{ i.goodsid.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ i.goodsid.shop_price }}</span>
						<span class="unit">{{ i.goodsid.shop_price }}/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}


			</ul>
		</div>
		</div>
	</div>

{% endblock %}

ttsx/templates/user_center_order.html
{% extends 'base_main.html' %}

{% block title %}
    我的订单
{% endblock %}

    {% block body %}
	<div class="search_bar clearfix">
		<a href="{% url 'user:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:UserCenter' %}"> · 个人信息</a></li>
				<li><a href="{% url 'goods:index' %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'order:index' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">未支付</li>		
				</ul>




				<table class="order_list_table w980">
					<tbody>

                        {% for user in users %}
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src='/{{ user.goods_front_image }}'></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>
									<li class="col03">1</li>
									<li class="col04">11.80元</li>
								</ul>

							</td>
							<td width="15%">33.60元</td>
							<td width="15%">待付款</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						</tr>
                        {% endfor %}
					</tbody>
				</table>

				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">已支付</li>
				</ul>

                    <table class="order_list_table w980">
					<tbody>

                        {% for user in users %}
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src='/{{ user.goods_front_image }}'></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>
									<li class="col03">1</li>
									<li class="col04">11.80元</li>
								</ul>

							</td>
							<td width="15%">33.60元</td>
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">评价</a></td>
						</tr>
                        {% endfor %}
					</tbody>
				</table>


				<div class="pagenation">
                    {% if users.has_previous%}
					<a href="{% url 'goods:index' %}?page={{ users.previous_page_number }}">上一页</a>
                    {% endif %}

                    {% for i in users.paginator.page_range %}
                        <a href="{% url 'goods:index' %}?page={{ i }}"  class="active">{{ i }}</a>
                    {% endfor %}

                    {% if users.has_next %}
					    <a href="{% url 'goods:index' %}?page={{ users.next_page_number }}">下一页</a>
                    {% endif %}
				</div>
		</div>
	</div>
    {% endblock %}